version: "3.9"
services:
  reverse-proxy:
    build: ./reverse-proxy
    environment:
      HTTPS: ${HTTPS}
      FRONTEND_DOMAIN_NAME: ${FRONTEND_DOMAIN_NAME}
      BACKEND_DOMAIN_NAME: ${BACKEND_DOMAIN_NAME}
      DOMAIN_VALIDATION_KEY: ${DOMAIN_VALIDATION_KEY}
    ports:
      - "80:80"
      - "443:443"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ${DATA_DIRECTORY}/reverse-proxy/etc-letsencrypt:/etc/letsencrypt/

  frontend:
    build: ./frontend
    environment:
      NODE_ENV: ${NODE_ENV}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_SENTRY_DSN: ${NEXT_PUBLIC_SENTRY_DSN}

  backend:
    build: ./backend
    env_file: ./backend/.env

  mapofpi_mongo:
    image: mongo:5.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - 27027:27017
    volumes:
      - ${DATA_DIRECTORY}/mongo/data:/data/db
